services:
  practice:
    build: .
    restart: always
    volumes:
      - ./:/practice
    command: >
      sh -c "uvicorn src.main:app --reload --host 0.0.0.0 --port 8000"
    ports:
      - '8000:8000'
    env_file:
      - .env
